
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cljwsvwfwxfhpnpzdikg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsandzdndmd3hmaHBucHpkaWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDAwMjMsImV4cCI6MjA2NDc3NjAyM30.dX2LE2foZL1ZOo0ctc_RKsdMExRambfx3btuJ9Wfh1Y";

// Validation des variables d'environnement
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Configuration Supabase manquante:', {
    url: !!SUPABASE_URL,
    key: !!SUPABASE_PUBLISHABLE_KEY
  });
  
  // En mode développement, on peut continuer avec des valeurs par défaut
  if (import.meta.env.DEV) {
    console.warn('Utilisation des valeurs Supabase par défaut en mode développement');
  } else {
    throw new Error('Les variables d\'environnement Supabase sont manquantes en production');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key'
);
