// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emodhgoanbxempznmxtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtb2RoZ29hbmJ4ZW1wem5teHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzI1MjYsImV4cCI6MjA2MzQwODUyNn0._YboHbJZeKvr31wJ9rQHGpF0Lgq4WGDNBgQu5d2c7Lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);